"""
Django settings for codacation project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import dj_database_url
from urllib.parse import urlparse

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.dirname(os.path.abspath(__file__))
    )
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', None)

ALLOWED_HOSTS = [
  'pallas.neutrondrive.com',
  'localhost.neutrondrive.com',
  
  'codacation.herokuapp.com',
  'codacation.com',
  'www.codacation.com',
]


# Application definition

INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'djzen',
  'django_uwsgi',
  'django_q',
  
  'social_django',
  'graphene_django',
  'rest_framework',
  
  'account',
  'classroom',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codacation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
          os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # Social Auth
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'codacation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {}
DATABASES['default'] = dj_database_url.config(
  default='postgres://postgres:postgres@localhost:5432/codacation')


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATICFILES_DIRS = [
  os.path.join(BASE_DIR, 'static'),
  os.path.join(BASE_DIR, 'node_modules', 'axios', 'dist'),
  os.path.join(BASE_DIR, 'node_modules', 'vue', 'dist'),
  os.path.join(BASE_DIR, 'node_modules', 'vue-router', 'dist'),
  os.path.join(BASE_DIR, 'node_modules', 'vue-material', 'dist'),
  os.path.join(BASE_DIR, 'node_modules', 'vuex', 'dist'),
]

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static-compiled")

# Uncomment for forever-cacheable files and compression support
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Uncomment if using Heroku
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False

GRAPHENE = {
  'SCHEMA': 'codacation.schema.schema'
}

REDIS = urlparse(os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0'))
REDIS_DB = 0
if REDIS.path:
  REDIS_DB = int(REDIS.path[1:])
  
Q_CLUSTER = {
  'name': 'codacation',
  'workers': 4,
  'recycle': 500,
  'timeout': 60,
  'compress': True,
  'save_limit': 250,
  'queue_limit': 500,
  'cpu_affinity': 1,
  'label': 'Django Q',
  'sync': True,
  'redis': {
    'host': REDIS.hostname,
    'port': REDIS.port,
    'db': REDIS_DB,
    'password': REDIS.password,
    
  }
}

from codacation.settings.auth import *

