# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 01:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='students',
            field=models.ManyToManyField(related_name='student_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='klass',
            name='admins',
            field=models.ManyToManyField(related_name='admin_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
